services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=healthmind-secret-key-must-be-at-least-256-bits-long

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=healthmind
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"